LLM_TEMP = 1
ENABLE_TESTING = True
GENERATE_REPORT = False
RETRY_ATTEMPT_LIMIT = 3

METRICS_OUTPUT_PATH = 'temp/output_metrics.json'
REPORT_PATH = 'temp/personal_finance_health_report.pdf'
REPORT_STYLESHEET = 'templates/pdf_templates/pdf_formatting.css'
LLM_OUTPUT_PATH = 'temp/llm_output.md'
REPORT_TEMPLATE_NAME = 'report_template.j2'
REPORT_TEMPLATE_DIR = 'templates/pdf_templates/'
GLOSSARY_PATH = 'assets/glossary.json'
LOGGING_DIR = 'logs/'
LOGGING_LIMIT_DAYS = 1

ANNUAL_INFLATION_RATE = 0.05
RETIREMENT_CORPUS_GROWTH_RATE = 0.08
AVG_LIFE_EXPECTANCY = 75
RETIREMENT_EXPENSE_REDUCTION_RATE = 0
MEDICAL_COVER_FACTOR = 500000
TERM_COVER_FACTOR = 10

SCORING_BASE_VALUE = 0.1